// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecAll.Contrib.MaksedTestList.Api.Services;

#nullable disable

namespace RecAll.Contrib.MaksedTestList.Api.Migrations
{
    [DbContext(typeof(MaskedTestListContext))]
    partial class MaskedTestListContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence("maskedtestlist_hilo")
                .IncrementsBy(10);

            modelBuilder.Entity("RecAll.Contrib.MaksedTestList.Api.Models.MaskedTestList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseHiLo(b.Property<int>("Id"), "maskedtestlist_hilo");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaskedContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaskedId")
                        .HasColumnType("int");

                    b.Property<string>("UserIdentityGuid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("MaskedId")
                        .IsUnique()
                        .HasFilter("[MaskedId] IS NOT NULL");

                    b.HasIndex("UserIdentityGuid");

                    b.ToTable("maskedtestlists", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
